services:
  - type: web
    name: task-api-service
    env: node
    region: virginia
    plan: free
    buildCommand: npm run migrate:deploy && npm run generate && npm run seed:prod
    startCommand: npm start
